# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_KGtools_rcpp_hello_world`)
}

rcppcor <- function(vec, mat) {
    .Call(`_KGtools_rcppcor`, vec, mat)
}

